# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClientDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CocoaAsyncSocket', '~> 7.6.5'

  # Pods for ClientDemo

  target 'ClientDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ClientDemoUITests' do
    # Pods for testing
  end

end
