# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# add flutter
flutter_application_path = '/Volumes/TwistedFateHD/GitLab/zhilun_merchant_flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'FlutterBLEDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  install_all_flutter_pods(flutter_application_path)
  
  # Pods for FlutterBLEDemo

  target 'FlutterBLEDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlutterBLEDemoUITests' do
    # Pods for testing
  end

end
