# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'SocketDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'CocoaAsyncSocket', '~> 7.6.5'
  
  use_frameworks!

  # Pods for SocketDemo

  target 'SocketDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SocketDemoUITests' do
    # Pods for testing
  end

end
